# Generated by Django 3.2 on 2023-04-23 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import wallets.models
import wallets.schemas


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='banks.bankaccount')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number', models.BigIntegerField(default=wallets.models.create_request_number, unique=True)),
                ('kind', models.CharField(choices=[(wallets.schemas.RequestKinds['Deposit'], 'Deposit'), (wallets.schemas.RequestKinds['Withdraw'], 'Withdraw')], default=wallets.schemas.RequestKinds['Withdraw'], max_length=10)),
                ('status', models.CharField(choices=[(wallets.schemas.RequestStates['Init'], 'Init'), (wallets.schemas.RequestStates['Pending'], 'Pending'), (wallets.schemas.RequestStates['Succeed'], 'Success'), (wallets.schemas.RequestStates['Failed'], 'Failed')], default=wallets.schemas.RequestStates['Init'], max_length=10)),
                ('amount', models.BigIntegerField()),
                ('scheduled_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='banks.bankaccount')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wallets.transaction')),
            ],
            options={
                'db_table': 'transaction_requests',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wallets.wallet'),
        ),
    ]
